import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "@/trpc/react";
import Header from "@/components/navbar/Header";
import { getServerSession } from "next-auth/next";
import { getServerAuthSession } from "@/server/auth";
import Footer from "@/components/landing/Footer";
import { getSession } from "next-auth/react";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await getServerAuthSession();



  return (
    <>
      {JSON.stringify(session)}
      <Header />
      <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-8">
        {children}
      </main>
      <Footer />
    </>

  );
}
